on: [push]

jobs: 
  build:
    run-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'
    - run: npm ci
    - run: npm run build
    - run: npm test